# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/searchMethod.ui'
#
# Created: Sat Nov  2 02:20:15 2013
#      by: pyside-uic 0.2.13 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_searchMethodMainWidget(object):
    def setupUi(self, searchMethodMainWidget):
        searchMethodMainWidget.setObjectName("searchMethodMainWidget")
        searchMethodMainWidget.resize(553, 414)
        self.gridLayout_2 = QtGui.QGridLayout(searchMethodMainWidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.searchBtn = QtGui.QPushButton(searchMethodMainWidget)
        self.searchBtn.setObjectName("searchBtn")
        self.gridLayout.addWidget(self.searchBtn, 1, 2, 1, 1)
        self.lookInsideLbl = QtGui.QLabel(searchMethodMainWidget)
        self.lookInsideLbl.setObjectName("lookInsideLbl")
        self.gridLayout.addWidget(self.lookInsideLbl, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lookInsideEdit = CompleterLineEdit(searchMethodMainWidget)
        self.lookInsideEdit.setAutoFillBackground(True)
        self.lookInsideEdit.setDragEnabled(True)
        self.lookInsideEdit.setObjectName("lookInsideEdit")
        self.horizontalLayout_3.addWidget(self.lookInsideEdit)
        self.label = QtGui.QLabel(searchMethodMainWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.lineEdit = QtGui.QLineEdit(searchMethodMainWidget)
        self.lineEdit.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_3.addWidget(self.lineEdit)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 1, 1, 1)
        self.addPathEdit = AddPathLineEdit(searchMethodMainWidget)
        self.addPathEdit.setInputMask("")
        self.addPathEdit.setObjectName("addPathEdit")
        self.gridLayout.addWidget(self.addPathEdit, 0, 1, 1, 1)
        self.addPathlbl = QtGui.QLabel(searchMethodMainWidget)
        self.addPathlbl.setObjectName("addPathlbl")
        self.gridLayout.addWidget(self.addPathlbl, 0, 0, 1, 1)
        self.browseBtn = QtGui.QPushButton(searchMethodMainWidget)
        self.browseBtn.setObjectName("browseBtn")
        self.gridLayout.addWidget(self.browseBtn, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.resultlbl = QtGui.QLabel(searchMethodMainWidget)
        self.resultlbl.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resultlbl.sizePolicy().hasHeightForWidth())
        self.resultlbl.setSizePolicy(sizePolicy)
        self.resultlbl.setMinimumSize(QtCore.QSize(0, 9))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.resultlbl.setFont(font)
        self.resultlbl.setObjectName("resultlbl")
        self.verticalLayout.addWidget(self.resultlbl)
        self.searchListView = QtGui.QListView(searchMethodMainWidget)
        self.searchListView.setMaximumSize(QtCore.QSize(16777215, 150))
        self.searchListView.setTabKeyNavigation(True)
        self.searchListView.setProperty("isWrapping", True)
        self.searchListView.setResizeMode(QtGui.QListView.Adjust)
        self.searchListView.setObjectName("searchListView")
        self.verticalLayout.addWidget(self.searchListView)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.methodListView = QtGui.QListView(searchMethodMainWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.methodListView.sizePolicy().hasHeightForWidth())
        self.methodListView.setSizePolicy(sizePolicy)
        self.methodListView.setMinimumSize(QtCore.QSize(20, 0))
        self.methodListView.setMaximumSize(QtCore.QSize(125, 16777215))
        self.methodListView.setObjectName("methodListView")
        self.gridLayout_3.addWidget(self.methodListView, 1, 0, 1, 1)
        self.helpOnSelMethodTxtEdit = QtGui.QTextEdit(searchMethodMainWidget)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.helpOnSelMethodTxtEdit.setFont(font)
        self.helpOnSelMethodTxtEdit.setProperty("cursor", QtCore.Qt.IBeamCursor)
        self.helpOnSelMethodTxtEdit.setFrameShape(QtGui.QFrame.StyledPanel)
        self.helpOnSelMethodTxtEdit.setFrameShadow(QtGui.QFrame.Raised)
        self.helpOnSelMethodTxtEdit.setTabChangesFocus(True)
        self.helpOnSelMethodTxtEdit.setReadOnly(True)
        self.helpOnSelMethodTxtEdit.setObjectName("helpOnSelMethodTxtEdit")
        self.gridLayout_3.addWidget(self.helpOnSelMethodTxtEdit, 1, 1, 1, 1)
        self.methodlbl = QtGui.QLabel(searchMethodMainWidget)
        self.methodlbl.setMinimumSize(QtCore.QSize(0, 9))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.methodlbl.setFont(font)
        self.methodlbl.setObjectName("methodlbl")
        self.gridLayout_3.addWidget(self.methodlbl, 0, 0, 1, 1)
        self.helplbl = QtGui.QLabel(searchMethodMainWidget)
        self.helplbl.setMinimumSize(QtCore.QSize(0, 12))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setBold(False)
        self.helplbl.setFont(font)
        self.helplbl.setObjectName("helplbl")
        self.gridLayout_3.addWidget(self.helplbl, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(searchMethodMainWidget)
        QtCore.QMetaObject.connectSlotsByName(searchMethodMainWidget)
        searchMethodMainWidget.setTabOrder(self.lookInsideEdit, self.lineEdit)
        searchMethodMainWidget.setTabOrder(self.lineEdit, self.searchBtn)
        searchMethodMainWidget.setTabOrder(self.searchBtn, self.searchListView)
        searchMethodMainWidget.setTabOrder(self.searchListView, self.addPathEdit)
        searchMethodMainWidget.setTabOrder(self.addPathEdit, self.browseBtn)

    def retranslateUi(self, searchMethodMainWidget):
        searchMethodMainWidget.setWindowTitle(QtGui.QApplication.translate("searchMethodMainWidget", "Search Method with help", None, QtGui.QApplication.UnicodeUTF8))
        self.searchBtn.setText(QtGui.QApplication.translate("searchMethodMainWidget", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.lookInsideLbl.setText(QtGui.QApplication.translate("searchMethodMainWidget", "Look Inside", None, QtGui.QApplication.UnicodeUTF8))
        self.lookInsideEdit.setToolTip(QtGui.QApplication.translate("searchMethodMainWidget", "modules or package names separated by comma", None, QtGui.QApplication.UnicodeUTF8))
        self.lookInsideEdit.setPlaceholderText(QtGui.QApplication.translate("searchMethodMainWidget", "Enter module name", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("searchMethodMainWidget", "Prefix", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit.setToolTip(QtGui.QApplication.translate("searchMethodMainWidget", "prefix to filter from all methods", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit.setPlaceholderText(QtGui.QApplication.translate("searchMethodMainWidget", "Enter starting letter/s or leave empty and hit enter", None, QtGui.QApplication.UnicodeUTF8))
        self.addPathEdit.setToolTip(QtGui.QApplication.translate("searchMethodMainWidget", "location of module or package not in sys.path", None, QtGui.QApplication.UnicodeUTF8))
        self.addPathEdit.setPlaceholderText(QtGui.QApplication.translate("searchMethodMainWidget", "Add path of the module or package not in sys.path list by default", None, QtGui.QApplication.UnicodeUTF8))
        self.addPathlbl.setText(QtGui.QApplication.translate("searchMethodMainWidget", "Add Path", None, QtGui.QApplication.UnicodeUTF8))
        self.browseBtn.setText(QtGui.QApplication.translate("searchMethodMainWidget", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.resultlbl.setText(QtGui.QApplication.translate("searchMethodMainWidget", "Results", None, QtGui.QApplication.UnicodeUTF8))
        self.methodlbl.setText(QtGui.QApplication.translate("searchMethodMainWidget", "Methods", None, QtGui.QApplication.UnicodeUTF8))
        self.helplbl.setText(QtGui.QApplication.translate("searchMethodMainWidget", "Help", None, QtGui.QApplication.UnicodeUTF8))

from autoComplete import CompleterLineEdit
from utils import AddPathLineEdit
